### ISSUE TITLE
[issue] CMS 去廣告，非Hermiru 的網址，解析卡頓。

### ISSUE THREAD

**Issue by linitfor** [Yswag/for-own-use#2]
想請教一下，例如使用量子 or 非凡資源CMS 影片時，
MITM 去解開資源網址後，似乎後續的解碼動作會很慢
導致影片出現卡頓的情形。
這個部分，您是否有方法可以解決呢?

PS. 使用loon 代理，加掛cmdAdblock.js

**Comment by Yswag** [comment]
你好，腳本只處理到返回m3u8的response，如果是播放到一半卡住的話就跟腳本無關了。
如果是指點擊播放後會等很久，有可能是去廣告解析長時間未響應才回退腳本處理，下次更新會移除解析只靠腳本去廣告

**Comment by linitfor** [comment]
請問"https://jscdn.centos.chat/bilfun.php/?url= " 只有提供解析替換腳本使用嗎?

指點擊播放後會等很久  => 偶爾，某些戲劇會
播放到一半卡住  => 這個較常發生

以下是我讀完您的腳本，自行解讀的想法:
資源: https://svipsvip.ffzy-online5.com/20240806/31051_23ca67cf/index.m3u8
因為MITM 網域 *ffzy*.com match
開啟解析替換成
https://svipsvip.ffzy-online5.com/20240806/31051_23ca67cf/2000k/hls/mixed.m3u8
然後解析腳本內部資料 (處理廣告)

然後再讓內部的 *.ts 逐條變成獨立的影音檔，提供播放  -> 
我再猜測是這個拆開的動作，會讓 "播放到一半卡住" 產生

**Comment by Yswag** [comment]
https://jscdn.centos.chat/bilfun.php/?url=
這是我在某線上看網站發現的去廣告解析，但似乎停止服務了，所以後續會移除

不 MITM 的話 .ts 也是逐條播放的，若是你測試不 MITM 跟 MITM 後有區別的話，那可能是 Loon 的 MITM 性能問題
像這種 .ts 跟 .m3u8 相同域名的話就只能全部都 MITM，因為只能指定到域名而已

另外非凡以及黑木耳後續也會移除，因為廣告算法升級已經沒辦法透過 m3u8 文件判斷哪幾個切片是廣告了

**Comment by linitfor** [comment]
喔喔 那有可能真的是Loon 的 MITM 性能的問題。
那請問大大改用其他app 的MITM 有遇到類似的問題嗎?
如果沒有遇到問題，是改用哪一個app 呢?

非凡近期的廣告分析起來是改成這段
![image](https://github.com/user-attachments/assets/9dd400b3-4fbc-4c3e-9712-c7048dad6be0)
但我遇到會卡頓，所以也沒真的開起來使用

黑木耳比較複雜，的確比較難精準移除
但他有兩種type
我是直接錯殺 XDD

**Comment by Yswag** [comment]
我日常使用是 Surge，不過最近也很少看劇，所以不清楚

我再測試一下非凡，感謝你

黑木耳我看過一種做法是取出DISCONTINUITY中的 ts 並用 md5 值來判斷，不過js腳本比較難做到，要再研究

**Comment by linitfor** [comment]
請問您使用Surge是買pro 版嗎?
我看mitm 要pro 版才支援
現在這個去廣告的script 一定要使用MITM嗎?
因為pro 版 好貴..... @@ 

ts 並用 md5 值來判斷 這個我沒看過
可以分享資料給我看看嗎?

不急，我也是業餘有時間，找topic 研究的 XD
我專業不是這個領域的.....

**Comment by Yswag** [comment]
你好，可以加我 [Telegram](https://t.me/ykusu)，比較方便溝通
